services:
  controle-share-videos-v1.0:
    container_name: controle-share-videos-v1.0
    build:
      context: .
      dockerfile: Dockerfile
    image: controle-share-videos-v1.0
  # To add ClamAV, to scan your shares for malicious files,


  
#docker compose build --no-cache
#docker compose up
#
#
